In [ ]:
#Hidden Markov Model
!pip install hmmlearn
import numpy as np
from hmmlearn import hmm

model = hmm.CategoricalHMM(
    n_components=2,
    n_iter=50
)

# Initial probabilities
model.startprob_ = np.array([0.6, 0.4])

# Transition probabilities
model.transmat_ = np.array([
    [0.7, 0.3],
    [0.4, 0.6]
])

model.emissionprob_ = np.array([
    [0.9, 0.1],  # State 0: probability of observing 0, probability of observing 1
    [0.2, 0.8]   # State 1: probability of observing 0, probability of observing 1
])

# Observations
# 0 = Umbrella, 1 = No Umbrella
# Observations for CategoricalHMM should be integer-encoded categories.
# The array O is already in the correct format.
O = np.array([[0], [0], [1], [0], [1]])

# Predict hidden states
states = model.predict(O)
print("Hidden states:", states)


# Train model
model.fit(O)

print("\nTrained start probabilities:")
print(model.startprob_)

print("\nTrained transition matrix:")
print(model.transmat_)

print("\nTrained emission matrix:")
print(model.emissionprob_)


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 kB 4.1 MB/s eta 0:00:00


Hidden states: [0 0 1 0 1]

Trained start probabilities:
[1.9343092e-13 1.0000000e+00]

Trained transition matrix:
[[7.92058843e-14 1.00000000e+00]
 [1.00000000e+00 2.28961548e-14]]

Trained emission matrix:
[[1.00000000e+00 1.46415978e-17]
 [3.33333333e-01 6.66666667e-01]]


In [ ]:
import numpy as np
from hmmlearn import hmm

model = hmm.CategoricalHMM(
    n_components = 2,
    n_iter = 50
)

model.startprob_ = np.array([0.6, 0.4])

model.transmat_ = np.array([
    [0.7, 0.3],
    [0.4, 0.6]
])

model.emissionprob_ = np.array([
    [0.9, 0.1],
    [0.2, 0.8]
])

o = np.array([[0], [1], [1], [1], [0], [0], [0], [0], [1]])

states = model.predict(o)
print("Hidden States:", states)

model.fit(o)

print('\nTrained Start transition:')
print(model.startprob_)

print('\nTrained Transition Matrix:')
print(model.transmat_)

print("\nTrained Emission Matrix:")
print(model.emissionprob_)

Hidden States: [0 1 1 1 0 0 0 0 1]

Trained Start transition:
[0.85047081 0.14952919]

Trained Transition Matrix:
[[0.87113244 0.12886756]
 [0.00400209 0.99599791]]

Trained Emission Matrix:
[[0.51099082 0.48900918]
 [0.60552151 0.39447849]]
